import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/app/Providers";
import Footer from "@/components/Footer";
import Navbar from "../components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";

const inter= Inter( { subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Providers>
          <ToastContainer/>
          <Navbar/>
          {children}
          <Footer/>
          </Providers>
      </body>
    </html>
  );
}
